export const enum IconType {
    REDO = 'redo',
    SKIP = 'skip',
    ABORT = 'abort',
    AUDIT = 'audit',
    WORKFLOW = 'workflow',
    ACTION = 'action',
    MANUAL = 'manual',
    DECISION = 'decision',
    SCRIPT = 'script',
    TASK = 'task',
    ADD = 'add',
    SORT = 'sort',
    GROUP = 'group',
    KEEP = 'keep',
    HOSTS = 'hosts',
    EDIT = 'edit',
    EXEC_AUTO = 'auto_exec',
    EXEC_MANUAL = 'manual_exec',
    EXEC_WAIT = 'wait_exec',
}
